# installing assets: 'bundle install'
# local serve: 'bundle exec jekyll serve -b /blint'
# If you change this file, please restart the server process.
#
# You can access these variables via {{ site.title }}, {{ site.email }}, etc.

title: bLint
email: semagnum+blint@gmail.com
description: BLint Official Documentation
github_username: semagnum
logo: assets/img/blint-logo.png

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme